<?php $comp_details=$this->login_model->company_details(); ?>
    <link href="<?php echo base_url() ?>assets/css/pages/signin.css" rel="stylesheet" type="text/css">
    <div class="main-container">
		<!--<div class="banner">-->
		<!--   <img src="<?php echo $this->config->item('base_url'); ?>assets/img/terms.jpg" style="width: 100%;height: auto;">-->
		<!--</div>--> 
		<div class="container-fluid">
			<div class="aboutus">
				<div class="container" >
					<div >
						<div class="row">
							<div class="col-md-12">							
								<div align="center"><legend class="head" >Terms and Conditions</legend></div>
							   <h4 style="line-height: 2;    color: #4B5E71; font-weight: 600;">Welcome to <?php echo $comp_details['company_name']; ?> Saving Scheme</h4>
							   <h4 class="page-subheading" style="font-weight: bold;">Terms of use</h4>
							   <p align="justify" class="conditions">&nbsp;Please read these terms of use carefully before using this website. If you do not agree to this Terms of Use you may not use this Website. By using this Website, you signify your explicit assent to this Terms of Use as well as the Website's Privacy Policy (which is hereby incorporated by reference herein). These Terms of Use sets out the legally binding terms of services available on the Website as well as at the terms of use of this Website. These Terms of Use along with the Privacy Policy extends to both users, who visit the Website but do not transact business on the Website ("Users / Guests") as well as users who are registered with by the Website to transact business on the Website ("Members"). The Company reserves the right to modify or terminate any portion of the Website or the Services offered by the Company for any reason, without notice and without liability to you or any third party. You are responsible for regularly reviewing these Terms of Use so that you will be apprised of changes, if any. Nothing in these Terms of Use should be construed to confer any rights to third party beneficiarie.</p>
							   <h4 class="page-subheading" style="font-weight: bold;">Description of Services</h4>	
							   <p align="justify" class="conditions">&nbsp; This Website provides access to trading, pricing, news and other information services related to <?php echo $comp_details['company_name']; ?> . Certain Services available on this Website are for the use of Members only. Please note that some of the terms under these Terms of Use, differ for purchases for personal consumption and for investment purposes.
								This Website offers services for Members who wish to purchase <?php echo $comp_details['company_name']; ?> for personal consumption, inclusive of, customized and readymade Jewellery. Some items may appear slightly larger or smaller than actual size due to screen defaults and photography techniques. Sometimes the items may be represented larger than the actual size in order to clearly show details or smaller than the actual size in order to show the entire item. The Company shall not be liable for any legal action on this account.</p>
							   <h4 class="page-subheading" style="font-weight: bold;">User Registration</h4>						
								<p align="justify" class="conditions">Users may register on the Website to become Members prior to the completion of any transaction on the Website.</p>						
								<p align="justify" class="conditions">To register onto the Website the User will have to provide Personal Information (as defined in the Privacy Policy), including but not limited name, e-mail, contact number, contact address which will be used for verification purposes.</p>	
								<p align="justify" class="conditions">Registration is only a one-time process and if the Member has previously registered, he/she shall log in/sign into his / her account.</p>
								<h4 class="page-subheading" style="font-weight: bold;">Terms & Conditions of use of the website</h4>	<h4 class="page-subheading" style="font-weight: bold;">BY USING THIS WEBSITE YOU REPRESENT AND WARRANT THAT:</h4>				
								<p>You are 18 years of age or older and that your use of the Website and/or Services shall not violate any applicable law or regulation.</p>						
								<p>All registration information you submit is truthful and accurate and that you agree to maintain the accuracy of such information.</p>						
								<p>Your membership is solely for your personal and non-commercial use. Any use of this Website or its content other than for personal purposes is prohibited.</p>						
								<p>Your personal and non-commercial use of this Website shall be subjected to the following restriction (i) you may not modify any content of the Website, including but not limited to, any public display, description, performance, sale, rental, pricing of the product; (ii) you may not decompile, reverse engineer, or disassemble the content, or (c) remove any copyright, trademark registration, or other proprietary notices from the content. You further agree not to access or use this Website in any manner that may be harmful to the operation of this Website or its content</p>	
								<p>You will not (a) use any product or service available on the Website and / Services for commercial purposes of any kind, or (b) advertise or sell any products, services or otherwise (whether or not for profit), or solicit others (including, without limitation, solicitations for contributions or donations) or use any public forum for commercial purposes of any kind, or (c) use the Website and / or Services in any way that is unlawful, or harms <?php echo $comp_details['website']; ?>  or any other person or entity, as determined in the <?php echo $comp_details['website']; ?>  sole discretion.</p>					
								<p>You will not post, submit, upload, distribute, or otherwise transmit or make available any software or other computer files that contain a virus or other harmful component, or otherwise impair or damage the Website and / or Services or any connected network, or otherwise interfere with any person or entity's use or enjoyment of the Website and / or Services</p>	<p >You will not engage in any form of antisocial, disrupting, or destructive acts, including "flaming," "spamming," "flooding," "trolling," "phishing" and "griefing" as those terms are commonly understood and used on the Internet.</p>				
								<p>You will not delete or modify any content of the Website and/or Services, including but not limited to, legal notices, disclaimers or proprietary notices such as copyright or trademark symbols, logos, that you do not own or have express permission to modify.</p>					
								<p><?php echo $comp_details['website']; ?>  cannot and will not assure that other users are or will be complying with the foregoing rules or any other provisions of this Terms of Use, and, as between you and <?php echo $comp_details['website']; ?> , you hereby assume all risk of harm or injury resulting from any such lack of compliance.</p>						
								<p>All information, content and material contained in the Website and/or Services are <?php echo $comp_details['website']; ?>  copyrighted property. All trademarks, service marks, trade names, and trade dress are proprietary to <?php echo $comp_details['website']; ?> . No information, content or material from the Website and/or Services may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way without the <?php echo $comp_details['website']; ?>  's express written permission</p>						
								<p>You acknowledge that when you access a link that leaves the Website, the site you will enter into is not controlled by <?php echo $comp_details['website']; ?>  and different terms of use and privacy policy may apply. By accessing links to other sites, you acknowledge that <?php echo $comp_details['website']; ?>  is not responsible for those sites. <?php echo $comp_details['website']; ?>  reserves the right to disable links from third-party sites to the Website, although <?php echo $comp_details['website']; ?>  is under no obligation to do so.</p>						
								<h4 class="page-subheading" style="font-weight: bold;">YOU EXPRESSLY UNDERSTAND AND AGREE THAT:</h4>						
								<p>The information, content and materials on this website and/or services are provided on an "as is" and "as available" basis. <?php echo $comp_details['website']; ?>  and all its affiliates, officers, employees, agents, partners and licensors disclaim all warranties of any kind, either express or implied, including but not limited to, implied warranties on merchantability, fitness for a particular purpose and non-infringement.</p>						
								<p><?php echo $comp_details['website']; ?>  makes all reasonable efforts to display the products listed for sale on its website(s) as accurately as possible. However, <?php echo $comp_details['website']; ?>  cannot guarantee that your monitor's display of any product colour, texture or detail will be accurate. <?php echo $comp_details['website']; ?>  does not warrant that product description or other content are accurate, complete, reliable current or error-free. While <?php echo $comp_details['website']; ?>  makes every effort to ensure that the products are described and priced accurately, in the event that an item is deemed to be priced incorrectly, <?php echo $comp_details['website']; ?>  reserves the right to refuse the sale of that item</p>				
								<p><?php echo $comp_details['website']; ?>  does not warrant that the functions contained in content, information and materials on the website and/or services, including, without limitation any third party sites or services linked to the website and/or services will be uninterrupted, timely or error-free, that the defects will be rectified, or that the website or the servers that make such content, information and materials available are free of viruses or other harmful components.</p>	
								<p>Any material downloaded or otherwise obtained through the website and/or services are accessed at your own risk, and you will be solely responsible for any damage or loss of data that results from such download to your computer system.</p>						
								<p>You hereby indemnify, defend, and hold <?php echo $comp_details['website']; ?>  , <?php echo $comp_details['website']; ?>  's distributors, agents, representatives and other authorized users, and each of the foregoing entities' respective resellers, distributors, service providers and suppliers, and all of the foregoing entities' respective officers, directors, owners, employees, agents, representatives, harmless from and against any and all losses, damages, liabilities and costs arising from your use of the website.</p>						
								<p>You expressly understand that under no circumstances, including, but not limited to, negligence, shall the company be liable to you or any other person or entity for any direct, indirect, incidental, special, or consequential damages, including, but not limited to damages for loss of profits, goodwill, use, data or other intangible losses, resulting from circumstances, including but not limited to: (i) the use or the inability to use the website and / or services; or (ii) the cost of procurement of substitute goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the website and / or services or (iii) unauthorized access to or alteration of your transmissions or data; (iv) statements or conduct of any third party on the website and / or services; or (v) any other matter relating to the website and / or services.</p>						
								<p><?php echo $comp_details['website']; ?>  or any of the foregoing entities' respective resellers, distributors, service providers and suppliers be relieved of all its responsibilities, if any, in the event of failure of performance resulting directly or indirectly from an act of force majeure or causes beyond the company's reasonable control including, without limitation, acts of God, war, equipment and technical failures, electrical power failures or fluctuations, strikes, labour disputes, riots, civil disturbances, shortages of labour or materials, natural disasters, orders of domestic or foreign courts or tribunals, non-performance of third parties, or any reasons beyond the reasonable control of the company or any of the foregoing entities' respective resellers, distributors, service providers and suppliers. You further acknowledge and agree that neither the company nor any of the foregoing entities' respective resellers, distributors, service providers and suppliers are responsible or liable for (a) any incompatibility between the website and / or services and any other website, service, software or hardware or (b) any delays or failures you may experience with any transmissions or transactions relating to the website in an accurate or timely manner. Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of liability for incidental or consequential damages. Accordingly, some of the above limitations of may not apply to you.</p>						
								<p>Each paragraph, clause, sub-clause and provision of this terms of use shall be severable from each other and if for any reason any paragraph, clause, sub-clause or provision is invalid or unenforceable, such invalidity or enforceability shall not prejudice or in any way affect the validity or enforceability of any other paragraph, clause, sub-clause or provision, which shall be read and construed so as to give thereto, the full effect thereof, subject only to any contrary provision of the law to the effect that where this provision of this terms of use or any paragraph, clause, sub-clause or provision hereof would be but for the provisions of this paragraph read and construed as being void or ineffective it shall nevertheless be a valid terms of use, paragraph, clause, sub-clause or provision, as the case may be, to the full extent to which it is not contrary to any provision of the law.</p>						
								<p>Those who access the website and/or services do so, on their own initiative and are responsible for compliance with all applicable laws including, but not limited to, any applicable local laws. These terms of use are governed by the laws of India. Any action, suit, or other legal proceedings, which is commenced to resolve any matter arising under or relating to this letter, shall be subject to the jurisdiction of the courts at Coimbatore.</p>						
								<p>All the contents on the website, of any manner, whatsoever, is Copyrighted work is protected under Indian Copyright Act, 1957. The unauthorized reproduction and distribution of our Copyrighted Work via the internet without our express permission constitute copyright infringement under the Copyright Act, 1957. Your act of infringement of our Copyrighted copyright and proprietary right makes you liable for action in law that includes prosecution under the Code of Civil Procedure, 1908 and Code of Criminal Procedure, 1.93</p>						
								<p>In the event of a breach of the terms and conditions of this terms of use by the user, the user shall be promptly liable to indemnify <?php echo $comp_details['website']; ?>  for all the costs, losses and damages caused to <?php echo $comp_details['website']; ?>  as a result of such a breach. Further, in the event of your breach of this terms of use, you agree that <?php echo $comp_details['website']; ?>  will be irreparably harmed and will not have an adequate remedy in money or damages. <?php echo $comp_details['website']; ?> , therefore, shall be entitled in such event to obtain an injunction against such a breach from any court of competent jurisdiction immediately upon request. <?php echo $comp_details['website']; ?>  's right to obtain such relief shall not limit its right to obtain other remedies.</p>						
								<p>Any failure of <?php echo $comp_details['website']; ?>  to exercise or enforce any right or provision of these terms of use shall not operate as a waiver of such right or provision.</p>						
								<p class="bottom-indent" style="line-height: 1.9; font-weight: bold;" align="">I HAVE READ THE TERMS OF USE AND AGREE TO ALL OF THE PROVISIONS CONTAINED ABOVE.</p>                    
                            </div> 
					    </div>
					</div>
				</div>
			</div>
		</div>
    </div>
